

services:
  # nginx:
  #   build: requirments/nginx
  #   ports:
  #     - 443:443
  #   networks:
  #     app:
  #       ipv4_address: 10.10.10.2
  #   volumes:
  #     - WordPress:/var/www/html
  
  mariadb:
    build: requirments/mariadb
    networks:
      app:
        ipv4_address: 10.10.10.3
    volumes:
      - DB:/var/lib/mysql
  
  # wordpress:
  #   build: requirments/wordpress
  #   networks:
  #     app:
  #       ipv4_address: 10.10.10.4
  #   volumes:
  #     - WordPress:/var/www/html

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.10.0/24"
volumes:
  DB:
  WordPress: