
services:
  nginx:
    build: requirments/nginx
    networks:
      - internal
    volumes:
      - wordpress:/var/www/html/
    ports:
      - 443:443


networks:
  internal:

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/wordpress"
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/mariadb"
